apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: {template-storage-image}
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "40m"
          limits:
            memory: "256Mi"
            cpu: "80m"
  strategy:
    type: RollingUpdate

