apiVersion: apps/v1
kind: Deployment
metadata:
  name: scientist-deployment
  namespace: business
  labels:
    app: scientist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scientist
  template:
    metadata:
      labels:
        app: scientist
    spec:
      containers:
      - name: scientist
        image: {template-scientist-image}
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
        env:
        - name: KAFKA_SERVER
          value: {template-kafka-server}
        - name: KAFKA_USER
          value: {template-kafka-user}
        - name: KAFKA_PASSWORD
          value: {template-kafka-password}
        resources:
          requests:
            memory: "128Mi"
            cpu: "40m"
          limits:
            memory: "256Mi"
            cpu: "80m"
  strategy:
    type: RollingUpdate

