apiVersion: v1
kind: Service
metadata:
  name: graylog-service
spec:
  selector:
    app: graylog
  ports:
  - port: 5044 # beats
    targetPort: 5044
    protocol: tcp
  - port: 5140 # Syslog
    targetPort: 5140
    protocol: udp
  - port: 5140 # Syslog
    targetPort: 5140
    protocol: tcp
  - port: 5555  # RAW TCP
    targetPort: 5555
    protocol: tcp
  - port: 5555 # RAW TCP
    targetPort: 5555
    protocol: udp 
  - port: 9000  # Server API
    targetPort: 9000
    protocol: tcp
  - port: 12201 # GELF TCP
    targetPort: 12201
    protocol: tcp
  - port: 12201 # GELF UDP
    targetPort: 12201
    protocol: udp
  - port: 13301 # Forwarder data
    targetPort: 13301
    protocol: tcp
  - port: 13302 # Forwarder config
    targetPort: 13302
    protocol: tcp
  type: ClusterIP