apiVersion: v1
kind: Service
metadata:
  name: graylog-service
spec:
  selector:
    app: graylog
  ports:
  - name: datanode-api
    protocol: TCP
    port: 8999
    targetPort: 8999
  - name: datanode-tcp-1
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: datanode-tcp-2
    port: 9300
    protocol: TCP
    targetPort: 9300
  - name: beats
    protocol: TCP
    port: 5044
    targetPort: 5044
  # - name: syslog-udp
  #   protocol: UDP
  #   port: 5140
  #   targetPort: 5140
  # - name: syslog-tcp
  #   protocol: TCP
  #   port: 5140
  #   targetPort: 5140
  - name: raw-tcp
    protocol: TCP
    port: 5555
    targetPort: 5555
  - name: raw-udp
    protocol: UDP 
    port: 5555
    targetPort: 5555
  - name: server-api
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: gelf-tcp
    protocol: TCP
    port: 12201
    targetPort: 12201
  - name: gelf-udp
    protocol: UDP
    port: 12201
    targetPort: 12201
  - name: forward-data
    protocol: TCP
    port: 13301
    targetPort: 13301
  - name: forward-config
    protocol: TCP
    port: 13302
    targetPort: 13302
  type: ClusterIP