apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-deployment
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:6.1.4
        ports:
        - containerPort: 5044 # beats
          protocol: TCP
        - containerPort: 5140 # Syslog
          protocol: UDP
        - containerPort: 5140 # Syslog
          protocol: TCP
        - containerPort: 5555  # RAW TCP
          protocol: TCP
        - containerPort: 5555 # RAW TCP
          protocol: UDP 
        - containerPort: 9000  # Server API
          protocol: TCP
        - containerPort: 12201 # GELF TCP
          protocol: TCP
        - containerPort: 12201 # GELF UDP
          protocol: UDP
        - containerPort: 13301 # Forwarder data
          protocol: TCP
        - containerPort: 13302 # Forwarder config
          protocol: TCP
        env:
        - name: GRAYLOG_NODE_ID_FILE
          value: /usr/share/graylog/data/config/node-id
        - name: GRAYLOG_PASSWORD_SECRET
          value: ${template-graylog-password-secret}
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: ${template-graylog-root-password-sha2}
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          value: 0.0.0.0:9000
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: "http://analysis.devsquare.ru/infra/graylog/"
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: https://{template-graylog-opensearch-user}:{template-graylog-opensearch-password}@192.168.0.10
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://{template-graylog-mongo-user}:{template-graylog-mongo-password}@192.168.0.9:27017/graylog?authSource=admin
        livenessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
  strategy:
    type: RollingUpdate


