apiVersion: apps/v1
kind: Deployment
metadata:
  name: uis-deployment
  labels:
    app: uis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uis
  template:
    metadata:
      labels:
        app: uis
    spec:
      containers:
      - name: uis
        image: {template.uis.image}
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: Repositories__SessionRepository__User
          vale: {template.repository.session.user}
        - name: Repositories__SessionRepository__Password
          vale: {template.repository.session.password}
        - name: Repositories__UserRepository__User
          vale: {template.repository.user.user}
        - name: Repositories__UserRepository__Password
          vale: {template.repository.user.password}
        - name: Gateways__GitHub__ClientId
          value: {template.gateway.github.clientid}
        - name: Gateways__GitHub__Secret
          value: {template.gateway.github.secret}
  strategy:
    type: RollingUpdate

