apiVersion: apps/v1
kind: Deployment
metadata:
  name: uis-deployment
  labels:
    app: uis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uis
  template:
    metadata:
      labels:
        app: uis
    spec:
      containers:
      - name: uis
        image: {template-uis-image}
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        env:
        - name: Repositories__SessionRepository__User
          value: {template-repository-session-user}
        - name: Repositories__SessionRepository__Password
          value: {template-repository-session-password}
        - name: Repositories__UserRepository__User
          value: {template-repository-user-user}
        - name: Repositories__UserRepository__Password
          value: {template-repository-user-password}
        - name: Gateways__GitHub__ClientId
          value: {template-gateway-github-clientid}
        - name: Gateways__GitHub__ClientSecret
          value: {template-gateway-github-secret}
        resources:
          requests:
            memory: "128Mi"
            cpu: "30m"
          limits:
            memory: "256Mi"
            cpu: "40m"
  strategy:
    type: RollingUpdate

