apiVersion: apps/v1
kind: Deployment
metadata:
  name: uis-deployment
  labels:
    app: uis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uis
  template:
    metadata:
      labels:
        app: uis
    spec:
      containers:
      - name: uis
        image: uis-image
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
  strategy:
    type: RollingUpdate

