apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
  labels:
    app: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: krakend:13
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /__health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
  strategy:
    type: RollingUpdate