apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: business-logic-services
spec:
  ingressClassName: nginx
  rules:      
  - host: api.analysis.devsquare.ru
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend: 
              service: 
                name: user-service-aspnet-core 
                port: 
                  number: 80
          - path: /studies
            pathType: Prefix
            backend: 
              service: 
                name: studies-service-aspnet-core
                port: 
                  number: 80 
          - path: /datasets
            pathType: Prefix
            backend: 
              service: 
                name: storage-service-aspnet-core
                port: 
                  number: 80 