POST http://api.analysis.devsquare.ru/user/login
Accept: application/json
Content-Type: application/json

{
    "token": ""
}

### 
POST   http://api.analysis.devsquare.ru/user/logout
Accept: application/json
Cookie: SessionId=

###
GET  http://api.analysis.devsquare.ru/user
Accept: application/json
Cookie: SessionId=

###
POST   http://api.analysis.devsquare.ru/datasets
Accept: application/json
Cookie: SessionId=
Content-Type: text/csv
Content-Disposition: attachment; filename=iris3.csv; filename*=UTF-8''iris.csv

< ./iris.csv

###
GET    http://api.analysis.devsquare.ru/datasets/description
Accept: application/json
Cookie: SessionId=