# User
POST http://api.analysis.devsquare.ru/user/login
Accept: application/json
Content-Type: application/json

{
    "token": "9c2f93f7-2bd9-494e-9751-4a8ea1a3d7cd"
}

### 
POST http://api.analysis.devsquare.ru/user/logout
Accept: application/json
Cookie: SessionId=;

###
GET http://api.analysis.devsquare.ru/user
Accept: application/json
Cookie: SessionId=;

### Datasets
POST http://api.analysis.devsquare.ru/datasets
Accept: application/json
Cookie: SessionId=d4c8572d-58ce-4e69-adde-809b9495c8e0;
Content-Type: text/csv
Content-Disposition: attachment; filename=iris7.csv; filename*=UTF-8''iris.csv

< ./iris.csv

###
GET http://api.analysis.devsquare.ru/datasets/description
Accept: application/json
Cookie: SessionId=;

###
GET http://api.analysis.devsquare.ru/datasets/iris7/description
Accept: application/json
Cookie: SessionId=;

### Study
POST http://api.analysis.devsquare.ru/studies
Accept: application/json
Cookie: SessionId=2ffbd370-2e68-4ff8-b0e5-096ce1b3f511;
Content-Type: application/json

{
    "type": "clustering",
    "componets": 3,
    "dataset":{
        "name": "iris7",
        "columns": ["sepal_length","sepal_width"]
    }
}

###
GET http://api.analysis.devsquare.ru/studies
Accept: application/json
Cookie: SessionId=2ffbd370-2e68-4ff8-b0e5-096ce1b3f511;

###
GET http://api.analysis.devsquare.ru/studies/0c5daaff-a976-4a82-9bf8-a7a1f19e7db8
Accept: application/json
Cookie: SessionId=2ffbd370-2e68-4ff8-b0e5-096ce1b3f511;

###
GET http://api.analysis.devsquare.ru/studies/0c5daaff-a976-4a82-9bf8-a7a1f19e7db8/result
Accept: application/json
Cookie: SessionId=2ffbd370-2e68-4ff8-b0e5-096ce1b3f511;


###
GET http://api.analysis.devsquare.ru/user/limits
Accept: application/json
Cookie: SessionId=9dd143bd-992f-4edb-9ee7-d08b9f806245;