apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: uis
        image: {template-frontend-image}
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
        env:
        - name: GITHUB_CLIENT_ID
          value: todo
  strategy:
    type: RollingUpdate

