appFromExternalRepo.enabled: false
global: 
  security: 
    allowInsecureImages: true
image:
  registry: ghcr.io
  repository: dmitriy770/analysis-study-service
command: ["dotnet", "app/StudyService.Api.dll"]

kong:
  extraEnvVars:
    - name: Producers__Study__Username
    - name: Producers__Study__Password

resourcesPreset: "micro"

customLivenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 3

containerPorts:
  http: 8080

service:
  type: ClusterIP
  ports:
    http: 80