apiVersion: apps/v1
kind: Deployment
metadata:
  name: scientist-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: scientist
        image: {template-scientist-image}
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
  strategy:
    type: RollingUpdate

