image:
  tag: 20.18.1-debian-12-r2

containerPorts:
  http: 3000

getAppFromExternalRepository: true
repository: https://github.com/Dmitriy770/analysis-webapp
revision: main

installCommand: ['ls', '&&', '/bin/bash', './src/frontend/deployment/init.sh']
command: ['/bin/bash', './src/frontend/deployment/entrypoint.sh']

mongodb:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 80

resources:
  requests:
     cpu: 100m
     memory: 128Mi
  limits:
     cpu: 100m
     memory: 128Mi
