name: '[deploy][business] StudyService'
run-name: deploy StudyService by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-study:
    name: Deploy study service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl and helm
        uses: ./.github/workflows/common/setup-helm.yaml

      - name: Helm deploy
        run: |
          cd ./src/StudyService/StudyService.Automation
          chmod 700 deploy.sh
          ./deploy.sh
        env:
          BRANCH: ${{ github.ref_name }}
          KAFKA_STUDY_SERVICE_BROKER_USER: ${{ secrets.KAFKA_STUDY_SERVICE_BROKER_USER }}
          KAFKA_STUDY_SERVICE_BROKER_PASSWORD: ${{ secrets.KAFKA_STUDY_SERVICE_BROKER_PASSWORD }}
