name: '[deploy][business] scientist service'
run-name: Deploy scientist service by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build scientist
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/scientist
          file: ./src/scientist/Dockerfile
          push: true
          tags: ghcr.io/dmitriy770/analysis-webapp-scientist:${{ github.run_id }}
          cache-from: type=gha,scope=container
          cache-to: type=gha,mode=max,scope=container
  
  deploy:
    name: Deploy scientist
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl and helm
        uses: ./.github/workflows/common/setup-helm
        with:
          kube_config: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy
        run: |
          cd ./src/scientist/deployment
          chmod 700 deploy.sh
          ./deploy.sh
        env:
          IMAGE_TAG: ${{ github.run_id }}
          KAFKA_USER: ${{ secrets.KAFKA_SCIENTIST_SERVICE_BROKER_USER }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_SCIENTIST_SERVICE_BROKER_PASSWORD }}