name: Build and deploy
run-name: Build and deploy by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      servicename:
        type: choice
        description: Service types
        options: 
        - uis
        - krakend
        - user-storage
        - session-storage
        - all

jobs:
  deploy-kraken:
    if: inputs.servicename == 'krakend' || inputs.servicename == 'all'
    uses: ./.github/workflows/krakend-deployment.yaml
    secrets: inherit
  
  deploy-uis:
    if: inputs.servicename == 'uis' || inputs.servicename == 'all'
    uses: ./.github/workflows/uis-deployment.yaml
    secrets: inherit
  
   deploy-user-storage:
    if: inputs.servicename == 'user-storage' || inputs.servicename == 'all'
    uses: ./.github/workflows/user-storage-deployment.yaml
    secrets: inherit
  
  deploy-session-storage:
    if: inputs.servicename == 'session-storage' || inputs.servicename == 'all'
    uses: ./.github/workflows/session-storage-deployment.yaml
    secrets: inherit

