name: Deploy
run-name: Deploy by @${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  build-uis:
    name: Build UIS
    runs-on: ubuntu-latest
    defaults:
      working-directory: './src/Uis'
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: /Uis.Api/Dockerfile
          push: true
          tags: ghcr.io/Dmitriy770/analysis-webapp-uis:${{github.run_id}}