name: '[deploy][business] scientist service'
run-name: Deploy scientist service by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build scientist
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/scientist
          file: ./src/scientist/Dockerfile
          push: true
          tags: ghcr.io/dmitriy770/analysis-webapp-scientist:${{github.run_id}}
  
  deploy:
    name: Deploy scientist
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Overwrite image for deployment
        run: sed -i 's\{template-scientist-image}\ghcr.io/dmitriy770/analysis-webapp-scientist:${{github.run_id}}\g' ./deployments/scientist/scientist-deployment.yaml

      - name: Setup kubectl and helm
        uses: ./.github/workflows/common/setup-helm
        with:
          kube_config: ${{ secrets.KUBE_CONFIG }}

      - name: Apply deployment
        run: kubectl apply -f ./src/scientist/deployment/scientist-deployment.yaml

      - name: Apply services
        run: kubectl apply -f ./src/scientist/deployment/scientist-service.yaml
