name: '[deploy][infra] Studies kafka'
run-name: deploy studies kafka by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Deploy studies kafka
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl and helm
        uses: ./.github/workflows/common/setup-helm
        with:
          kube_config: ${{ secrets.KUBE_CONFIG }}

      - name: Helm deploy studies kafka
        run: |
          cd ./infrastructure/studies-kafka/kafka
          chmod 700 deploy.sh
          ./deploy.sh
        env:
          KAFKA_UI_BROKER_USER: ${{ secrets.KAFKA_UI_BROKER_USER }}
          KAFKA_UI_BROKER_PASSWORD: ${{ secrets.KAFKA_UI_BROKER_PASSWORD }}
          KAFKA_STUDY_SERVICE_BROKER_USER: ${{ secrets.KAFKA_STUDY_SERVICE_BROKER_USER }}
          KAFKA_STUDY_SERVICE_BROKER_PASSWORD: ${{ secrets.KAFKA_STUDY_SERVICE_BROKER_PASSWORD }}
          KAFKA_SCIENTIST_SERVICE_BROKER_USER: ${{ secrets.KAFKA_SCIENTIST_SERVICE_BROKER_USER }}
          KAFKA_SCIENTIST_SERVICE_BROKER_PASSWORD: ${{ secrets.KAFKA_SCIENTIST_SERVICE_BROKER_PASSWORD }}
          KAFKA_CONTROLLER_USER: ${{ secrets.KAFKA_CONTROLLER_USER }}
          KAFKA_CONTROLLER_PASSWORD: ${{ secrets.KAFKA_CONTROLLER_PASSWORD }}
          KAFKA_INTERBROKER_USER: ${{ secrets.KAFKA_INTERBROKER_USER }}
          KAFKA_INTERBROKER_PASSWORD:  ${{ secrets.KAFKA_INTERBROKER_PASSWORD }}
        
      - name: Helm deploy kafka ui
        run: |
          cd ./infrastructure/studies-kafka/kafka-ui
          chmod 700 deploy.sh
          ./deploy.sh
        env:
          KAFKA_UI_BROKER_USER: ${{ secrets.KAFKA_UI_BROKER_USER }}
          KAFKA_UI_BROKER_PASSWORD: ${{ secrets.KAFKA_UI_BROKER_PASSWORD }}
          KAFKA_UI_USER_LOGIN: ${{ secrets.KAFKA_UI_USER_LOGIN }}
          KAFKA_UI_USER_PASSWORD: ${{ secrets.KAFKA_UI_USER_PASSWORD }}
