name: Deploy Graylog
run-name: DeployGraylog by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:
jobs:
  deploy-user-storage:
    name: Deploy Graylog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Overwrite password
        run: sed -i 's\{template-graylog-password-secret}\${{secrets.GRAYLOG_PASSWORD_SECRET}}\g' ./deployments/graylog/graylog-deployment.yaml

      - name: Overwrite sha2 password
        run: sed -i 's\{template-graylog-root-password-sha2}\${{secrets.GRAYLOG_ROOT_PASSWORD_SHA2}}\g' ./deployments/graylog/graylog-deployment.yaml

      - name: Overwrite mongo user
        run: sed -i 's\{template-graylog-mongo-user}\${{secrets.GRAYLOG_MONGO_USER}}\g' ./deployments/graylog/graylog-deployment.yaml

      - name: Overwrite mongo password
        run: sed -i 's\{template-graylog-mongo-password}\${{secrets.GRAYLOG_MONGO_PASSWORD}}\g' ./deployments/graylog/graylog-deployment.yaml

      - name: Overwrite opensearch user
        run: sed -i 's\{template-graylog-opensearch-user}\${{secrets.GRAYLOG_OPENSEARCH_USER}}\g' ./deployments/graylog/graylog-deployment.yaml

      - name: Overwrite opensearch password
        run: sed -i 's\{template-graylog-opensearch-password}\${{secrets.GRAYLOG_OPENSEARCH_PASSWORD}}\g' ./deployments/graylog/graylog-deployment.yaml

      - name: Apply deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/graylog/graylog-deployment.yaml

      - name: Apply services
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/graylog/graylog-service.yaml