name: Build and deploy KrakenD
run-name: KrakenD UIS by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-krakend:
    name: Build KrakenD
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./infrastructure/krakend
          file: ./infrastructure/krakend/Dockerfile
          push: true
          tags: ghcr.io/dmitriy770/analysis-webapp-krakend:${{github.run_id}}
  
  deploy-krakend:
    name: Deploy KrakenD
    runs-on: ubuntu-latest
    needs: [build-krakend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Overwrite image for deployment
        run: sed -i 's\{template.krakend.image}\ghcr.io/dmitriy770/analysis-webapp-krakend:${{github.run_id}}\g' ./deployments/krakend/krakend-deployment.yaml

      - name: Apply deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/krakend/krakend-deployment.yaml

      - name: Apply services
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/krakend/krakend-service.yaml
