name: Build and deploy Storage service
run-name: Deploy UIS by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-storage:
    name: Build Storage service
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/StorageService/StorageService.Api/Dockerfile
          push: true
          tags: ghcr.io/dmitriy770/analysis-storage-service:${{github.run_id}}
  
  deploy-storage:
    name: Deploy Storage service
    runs-on: ubuntu-latest
    needs: [build-storage]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Overwrite image for deployment
        run: sed -i 's\{template-storage-image}\ghcr.io/dmitriy770/analysis-storage-service:${{github.run_id}}\g' ./deployments/storage-service/storage-deployment.yaml

      - name: Apply deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/storage-service/storage-deployment.yaml

      - name: Apply services
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/storage-service/storage-service.yaml
