name: Build and deploy Study service
run-name: Deploy Study service by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-study:
    name: Build Study service
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/StudyService/StudyService.Api/Dockerfile
          push: true
          tags: ghcr.io/dmitriy770/analysis-study-service:${{github.run_id}}
  
  deploy-study:
    name: Deploy study service
    runs-on: ubuntu-latest
    needs: [build-study]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Overwrite image for deployment
        run: sed -i 's\{template-study-image}\ghcr.io/dmitriy770/analysis-study-service:${{github.run_id}}\g' ./deployments/study-service/study-deployment.yaml

      - name: Apply deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/study-service/study-deployment.yaml

      - name: Apply services
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/study-service/study-service.yaml
