name: Build and deploy Study service
run-name: Deploy Study service by @${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-study:
    name: Deploy study service
    runs-on: ubuntu-latest
    needs: [build-study]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Set kubectl context
        run: |
          mkdir "$HOME/.kube"
          touch "$HOME/.kube/config"
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > "$HOME/.kube/config"
      
      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Helm deploy
        run: |
          cd ./src/StudyService/StudyService.Automation
          chmod 700 deploy.sh
          ./deploy.sh
        env:
          BRANCH: ${{ github.ref_name }}
          KAFKA_STUDY_SERVICE_BROKER_USER: ${{ secrets.KAFKA_STUDY_SERVICE_BROKER_USER }}
          KAFKA_STUDY_SERVICE_BROKER_PASSWORD: ${{ secrets.KAFKA_STUDY_SERVICE_BROKER_PASSWORD }}
