name: Build and deploy UIS
run-name: Deploy UIS by @${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  build-uis:
    name: Build UIS
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/Uis
          file: ./src/Uis/Uis.Api/Dockerfile
          push: true
          tags: ghcr.io/dmitriy770/analysis-webapp-uis:${{github.run_id}}
  
  deploy-uis:
    name: Deploy UIS
    runs-on: ubuntu-latest
    needs: [build-uis]
    env:
      ConfigPath: ./deployments/uis/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Overwrite image for deployment
        run: sed -i 's\uis-image\ghcr.io/dmitriy770/analysis-webapp-uis:${{github.run_id}}\g' ./deployments/uis/uis-deployment.yaml

      - name: Apply deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/uis/uis-deployment.yaml

      - name: Apply services
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployments/uis//uis-service.yaml
